<?php
print '<h1>' . $post['title'] . '</h1>';
print '<div>' . $post['text'] . '</div>';
print '<li>
        <a href="' . $this->url('blog', array('action'=>'edit', 'id' => $post['id'])) . '">edit</a>,
        <a href="' . $this->url('blog', array('action'=>'delete', 'id' => $post['id'])) . '">delete</a>
      </li>';   
?>

<h2><?php echo " Add new comment" ?></h2>
<?php
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('comment'));
echo $this->formSubmit($form->get('submit'));
?>

<script src="./js/jquery-1.9.1.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    $("#submitbutton").click(function(){
        $.ajax({
            url: '/ajax/addcomment',
            type : 'POST',
            data: {data: $('#comment').val(), id: <?php echo $id_comment; ?>},
            dataType : "json",
        });
        $("#response").load('/ajax/addcomment');
    })
})
</script>

<h2><?php echo " All Comments" ?></h2>

<?php
foreach($this->comments as $comment) 
{
    print $comment['comment'].'<br>';
}
?>

<div id = "response"></div>

